### PR TITLE
DOC-7529: System keyspaces

### PR DESCRIPTION
**Pull request by simon-dew**
The following draft documentation is ready for review:

* [Getting System Information](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-intro/sysinfo.html)

Docs issue: [DOC-7529](https://issues.couchbase.com/browse/DOC-7529)

### CODE REVIEW

**Comment by marcogrecopriolo** [comment]
All perfect. Just one little note (and it's probably my bad...)
Aside from system:scopes, system:keyspaces, system:indexes, we also have system:all_scopes, system:all_keyspaces, system:all_indexes.
They look exactly the same as the non 'all_' counterpart, but also list system objects, so for instance system:all_scopes would list '_default' scopes, which system:scopes, wouldn't, system:all_keyspaces would list all the system keyspaces and would list  the same keyspace twice, once as default:bucket1 and once as default:bucket1._default._default, and system:all_indexes would also list indexes on system:keyspaces.

If you think these are confusing, we can just leave them undocumented.

**Comment by simon-dew** [comment]
Thanks @marcogrecopriolo. I've actually documented `system:all_scopes` as a note under the **Querying Scopes** heading, `system:all_keyspaces` as a note under the **Querying Collections** heading, and  `system:all_indexes` as a note under the **Querying Indexes** heading. I wanted to make sure they were documented, but didn't want to get bogged down in details because as you say the behavior of `system:all_keyspaces` is confusing.

**Comment by marcogrecopriolo** [comment]
perfect!

**Review by marcogrecopriolo — APPROVED** [review]

**Comment by simon-dew** [comment]
Update links to staging docs

**Pull request merged**
