### PR TITLE
DOC-9196: How-to Guides for Server Developers

### PR DESCRIPTION
**Pull request by simon-dew**
The following documentation is ready for final review before merging into release/7.0:

* [Developer Guides](https://simon-dew.github.io/docs-site/DOC-9196/server/7.0/guides/intro.html)

Please note that reorganizing the nav to move and rename the current *Learn* and *Manage* sections will be handled by DOC-9201 and DOC-9202.

Docs issue: [DOC-9196](https://issues.couchbase.com/browse/DOC-9196)
Dashboard: [Dev Reorganization Stage 1](https://hub.internal.couchbase.com/confluence/pages/viewpage.action?spaceKey=techpubs&title=Dev+Reorganisation+Stage+1)

### CODE REVIEW

**Comment by maria-robobug** [comment]
* I found the split of `Data Manipulation` and `Queries` a bit confusing in the left-hand nav, shouldn't the `Data Manipulation` sections all fall under `Queries`?

* Should the `KV Operations` page under `Developer Information` still be there? Seems like we can remove this page now: https://simon-dew.github.io/docs-site/DOC-9196/server/7.0/sdk/development-intro.html 

Just a couple of questions but looks good on my end from the quick glance I had 👍 .

**Comment by simon-dew** [comment]
> I found the split of `Data Manipulation` and `Queries` a bit confusing in the left-hand nav, shouldn't the `Data Manipulation` sections all fall under `Queries`?

Good point. I flattened the nav structure to make the how-to guides easier to find — I didn't want to have too many levels of categories and sub-categories.

- [x] Rename Queries → Selection Queries
- [x] Rename Data Manipulation → Data Manipulation Queries

> Should the `KV Operations` page under `Developer Information` still be there? Seems like we can remove this page now: https://simon-dew.github.io/docs-site/DOC-9196/server/7.0/sdk/development-intro.html

Yes, that's on my list, probably as part of DOC-9202. Added comment

**Comment by RayOffiah** [comment]
https://simon-dew.github.io/docs-site/DOC-9196/server/7.0/guides/reading-data.html

I'm not sure where you'd fit it in, so this is just a suggestion, but I wonder if it needs mentioning somewhere that you read until you've created an index.

Then again, since you're using the travel sample then it doesn't matter because you already have an index.

**Comment by osfameron** [comment]
I'm a bit confused by the "Deep Traversal for Nested Documents" section.

The first part on NEST looks like it should really be covered in the previous "Querying Across Relationships
" section: I guess the best path through is subjective - but note that the "Chaining Joins" section starts "To chain joins, nests, and unnests" where nests haven't been defined.

In fact I'm not sure that the section covers *traversal* as such? (the stem `travers` isn't used outside the title.)

**Comment by RayOffiah** [comment]
This is great. There's masses of stuff I don't know and this is a really good starting point.

The Data Manipulation section: I was thinking that Importing Data should go in here, maybe at the bottom, and transactions could go in there too. And I was thinking of Handling Data for the name.

**Comment by osfameron** [comment]
(musing for future: the design of /guides/intro.html could be made more card-like? 
Something along lines of https://developer.couchbase.com/tutorials perhaps?)

**Comment by RayOffiah** [comment]
> (musing for future: the design of /guides/intro.html could be made more card-like? Something along lines of https://developer.couchbase.com/tutorials perhaps?)

I like the card idea, but probably on a shorter page.

**Comment by osfameron** [comment]
> I like the card idea, but probably on a shorter page.

Hah yes, I think the cards would look better on our nice short guides page than they do on the longer DA one... :trollface:

**Comment by simon-dew** [comment]
> I'm a bit confused by the "Deep Traversal for Nested Documents" section.
> 
> The first part on NEST looks like it should really be covered in the previous "Querying Across Relationships " section: I guess the best path through is subjective - but note that the "Chaining Joins" section starts "To chain joins, nests, and unnests" where nests haven't been defined.

- [x] Renamed to "Nesting and Unnesting Documents". 

Joins, nests, and unnests are similar concepts, and they can all be chained together — it's hard to describe one without at least referring to the others. I introduced joins first as they are more likely to be familiar to SQL users,  of course.

**Review by maria-robobug — APPROVED** [review]

**Comment by simon-dew** [comment]
> I'm not sure where you'd fit it in, so this is just a suggestion, but I wonder if it needs mentioning somewhere that you read until you've created an index.
> 
> Then again, since you're using the travel sample then it doesn't matter because you already have an index.

- [x] Added note to Selection Query reinforcing the message that indexes are essential

**Pull request merged**
