### PR TITLE
Doc 4306

### PR DESCRIPTION
**Pull request by maheshnagarajCbase**
DOC-4306:Fixing Debug screenshot

### CODE REVIEW

**Comment by maheshnagarajCbase** [comment]
All merge conflicts have been resolved. PR is ready to be merged

**Comment by maheshnagarajCbase** [comment]
@amarantha-k : PR for your review. 

Changes: Updates to the debug source map screenshot

**Comment by amarantha-k** [comment]
Mahesh, this PR has a lot more commits than the fix you made yesterday. Please fix it.

**Review by amarantha-k — DISMISSED** [review]
Too many commits

**Comment by amarantha-k** [comment]
Closing PR for now. Please open a new one with specific changes if needed. Thanks!

**Pull request closed without merging**
