### PR TITLE
DOC-5140: as of the 6.5 beta, N1QL will only support GSI indexes

### PR DESCRIPTION
**Pull request by simon-dew**
The following draft documentation is ready for review.

Documentation issue [DOC-5140](https://issues.couchbase.com/browse/DOC-5140)

## DDL Changes

* [BUILD INDEX › Syntax › USING Clause](https://simon-dew.github.io/docs-site/DOC-5140/server/6.5/n1ql/n1ql-language-reference/build-index.html#index-using)
* [CREATE INDEX › Syntax › USING Clause](https://simon-dew.github.io/docs-site/DOC-5140/server/6.5/n1ql/n1ql-language-reference/createindex.html#index-using)
  - [Array Indexing › Syntax › USING Clause](https://simon-dew.github.io/docs-site/DOC-5140/server/6.5/n1ql/n1ql-language-reference/indexing-arrays.html#index-using)
  - [Covering Indexes](https://simon-dew.github.io/docs-site/DOC-5140/server/6.5/n1ql/n1ql-language-reference/covering-indexes.html) — removed references to view indexes
  - [Adaptive Index › Syntax › USING Clause](https://simon-dew.github.io/docs-site/DOC-5140/server/6.5/n1ql/n1ql-language-reference/adaptive-indexing.html#index-using)
  - [Index Partitioning › Syntax › USING Clause](https://simon-dew.github.io/docs-site/DOC-5140/server/6.5/n1ql/n1ql-language-reference/index-partitioning.html#index-using)
* [CREATE PRIMARY INDEX › Syntax › USING GSI](https://simon-dew.github.io/docs-site/DOC-5140/server/6.5/n1ql/n1ql-language-reference/createprimaryindex.html#syntax)
* [DROP INDEX › USING GSI](https://simon-dew.github.io/docs-site/DOC-5140/server/6.5/n1ql/n1ql-language-reference/dropindex.html)
* [DROP PRIMARY INDEX › USING GSI](https://simon-dew.github.io/docs-site/DOC-5140/server/6.5/n1ql/n1ql-language-reference/dropprimaryindex.html)

## DML Changes

* [SELECT Syntax › USE Clause](https://simon-dew.github.io/docs-site/DOC-5140/server/6.5/n1ql/n1ql-language-reference/select-syntax.html#use-clause)
* [USE Clause › USE INDEX Clause › Syntax › USING Clause](https://simon-dew.github.io/docs-site/DOC-5140/server/6.5/n1ql/n1ql-language-reference/hints.html#index-using)

## Other Changes

* [Conventions](https://simon-dew.github.io/docs-site/DOC-5140/server/6.5/n1ql/n1ql-language-reference/conventions.html) — removed `USING VIEW` example 
* [View Indexes for N1QL](https://simon-dew.github.io/docs-site/DOC-5140/server/6.5/learn/views/view-indexes-for-n1ql.html) — replaced with stub message and removed from ToC

### CODE REVIEW

**Comment by sitaramv** [comment]
FTS indexes are new in 6.5.0 , hope those covered

**Comment by simon-dew** [comment]
> FTS indexes are new in 6.5.0 , hope those covered

FTS indexes are covered for DML statements

* [SELECT Syntax › USE Clause](https://simon-dew.github.io/docs-site/DOC-5140/server/6.5/n1ql/n1ql-language-reference/select-syntax.html#use-clause)
* [USE Clause › USE INDEX Clause › Syntax › USING Clause](https://simon-dew.github.io/docs-site/DOC-5140/server/6.5/n1ql/n1ql-language-reference/hints.html#index-using)

**Comment by sitaramv** [comment]
This is contradicting from others

**Comment by simon-dew** [comment]
Please clarify, is it possible to use CREATE INDEX in N1QL to create an FTS index?

**Comment by sitaramv** [comment]
CREATE and DROP not possible.
USE INDEX  syntax (SELECT, UPDATE, DELETE, MERGE) is allowed FTS index.

**Comment by sitaramv** [comment]
This is DDL ok

**Review by sitaramv — APPROVED** [review]

**Comment by sitaramv** [comment]
DDL is fine. make sure DML includes both

**Comment by simon-dew** [comment]
> make sure DML includes both

FTS indexes were added to DML as part of a0a2839a

**Comment by simon-dew** [comment]
This PR removes VIEW indexes from DML

**Review by sitaramv — APPROVED** [review]

**Pull request merged**
