### PR TITLE
DOC-10328: improve pagination queries on fetch

### PR DESCRIPTION
**Pull request by simon-dew**
The following draft documentation is ready for review:

* [Early Filters, Order, and Pagination](https://simon-dew.github.io/docs-site/DOC-10328/server/current/learn/services-and-indexes/indexes/early-filters-and-pagination.html)

Docs issue: [DOC-10328](https://issues.couchbase.com/browse/DOC-10328)

### CODE REVIEW

**Comment by miaobingjie** [comment]
Can you also add Sitaram to the review? I think some sections related to index pushdowns need to be reworded. I'll send out my review comment later ...

**Review by sitaramv — COMMENTED** [review]
looks ok for me let bingjie review and approve

**Comment by miaobingjie** [comment]
Overview:

First paragraph, this is true for a query on a single keyspace, maybe change first sentence to reflect that.

Ealy Filtering:

Example 3: in the notes that explains the markings
  1), 2), 3) this looks fine
  4) "index_key" should be "_index_key"

Early Order and Pagination:
  looks fine

Limitations:
  looks fine

Caveats:
  I suggest we remove this whole section. This is for internal info and may cause unnecessary concerns if included.

Summary:
  I'm a bit unsure about the row marked "Supports grouping and aggregates?", can you double check with Sitaram on:
    - index pushdown: should it  be "No" instead of "Some"

**Review by sitaramv — COMMENTED** [review]
Summary:
I'm a bit unsure about the row marked "Supports grouping and aggregates?", can you double check with Sitaram on:
- index pushdown: should it be "No" instead of "Some"


I have never seen this. I clicked on Files Changed and did not see any changes there mentioned above

**Review by sitaramv — COMMENTED** [review]
Bingjie is right change to 
Supports grouping and aggregates? | Some | No | No | Yes

**Comment by simon-dew** [comment]
> Bingjie is right change to Supports grouping and aggregates? | Some | No | No | Yes

On further thought, I might just remove the grouping and aggregates row from the summary table because it is distracting from the essential points.

**Comment by simon-dew** [comment]
- [x] First paragraph, this is true for a query on a single keyspace, maybe change first sentence to reflect that.
- [x] Early Filtering, Example 3: (4) "index_key" should be "_index_key"
- [x] Caveats: I suggest we remove this whole section.
- [x] "Supports grouping and aggregates?"

**Pull request merged**
