### PR TITLE
DOC-7457: Updates to CBO

### PR DESCRIPTION
**Pull request by simon-dew**
The following draft documentation is ready for review:

* [UPDATE STATISTICS](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/updatestatistics.html) overview — removed DP, added system collection
* [Updating Statistics for Index Expressions](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/statistics-expressions.html)
* [Updating Statistics for a Single Index](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/statistics-index.html)
* [Updating Statistics for Multiple Indexes](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/statistics-indexes.html)
* [Deleting Statistics](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/statistics-delete.html)
* [Cost-Based Optimizer](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/cost-based-optimizer.html) — removed DP

Docs issue: [DOC-7457](https://issues.couchbase.com/browse/DOC-7457)

### CODE REVIEW

**Comment by simon-dew** [comment]
- [x] link to `use_cbo` setting

**Comment by simon-dew** [comment]
- [x] Multiple indexes: tighten up wording on subqueries

**Comment by miaobingjie** [comment]
In "Update Statistics for a Single Index", under keyspace_ref, if the keyspace is a collection, I believe you need to specify the full path including the namespace part (i.e. namespace is not optional). This should be the same as in DROP INDEX or ALTER INDEX statement. Maybe add a comment after the syntax diagram to say that if a full path for a collection is used, you must include namespace, bucket, scope and collection names. Check with Marco if necessary.

**Comment by simon-dew** [comment]
> In "Update Statistics for a Single Index", under keyspace_ref, if the keyspace is a collection, I believe you need to specify the full path including the namespace part (i.e. namespace is not optional). This should be the same as in DROP INDEX or ALTER INDEX statement. Maybe add a comment after the syntax diagram to say that if a full path for a collection is used, you must include namespace, bucket, scope and collection names. Check with Marco if necessary.

Done

**Comment by simon-dew** [comment]
Update links to staging docs

**Pull request merged**
