### PR TITLE
flex-indexes.adoc small corrections

### PR DESCRIPTION
**Pull request by BKaneAtWork**
Correct array example and hint

### CODE REVIEW

**Comment by BKaneAtWork** [comment]
@couchbase/docs-team please review

**Review by simon-dew — APPROVED** [review]
LGTM 👍

**Comment by simon-dew** [comment]
Can't merge this forward as the SQL++ reference was moved to docs-devex. Will need separate PR.

**Comment by BKaneAtWork** [comment]
Ok, new PR is https://github.com/couchbaselabs/docs-devex/pull/286

**Comment by simon-dew** [comment]
> Can't merge this forward as the SQL++ reference was moved to docs-devex. Will need separate PR.

Sorry for the confusion, this was more of a note to myself! No further action needed

**Pull request merged**
