### PR TITLE
DOC-12448 ubuntu 24.04 support

### PR DESCRIPTION
**Pull request by ggray-cb**
* Added Ubuntu 24.04 to satisfy DOC-12448
* Added general guidelines about virtualized and containerized environments using supported OSes mainly for [DOC-10639](https://jira.issues.couchbase.com/browse/DOC-10639).
* Reordered some the version numbers in the list of supported OSes so they consistently go from high to low (some went from low to high).
* Added bullets to supported OS list to help readability.
* Misc. rewording/depassivefying.
* Added Windows 11 as a supported platform, as apparently it's been [supported since 7.1](https://jira.issues.couchbase.com/browse/MB-52138). Windows 10 deprecation is a separate issue.

Preview: https://preview.docs-test.couchbase.com/DOC-12448_ubuntu_24.04_support/server/current/install/install-platforms.html

[DOC-10639]: https://couchbasecloud.atlassian.net/browse/DOC-10639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by malarky** [comment]
I think perhaps a more general statement on virtualization is that the VM or container that Couchbase Server is running in has to be a supported OS, but the OS of underlying host does not matter.  For example, in VMware, the "host" is usually [ESXi](https://en.wikipedia.org/wiki/VMware_ESXi), a very minimal Linux-based hypervisor.

**Comment by ggray-cb** [comment]
Ok, removed the OS requirement statements for Docker, VMs, and the like, and added a general statements about cotainers and VM using one of the approved OSes, but the host OS is irrelevant.

**Comment by ggray-cb** [comment]
@malarky Can you take a look a the updated PR? I'd like to get this in before I start on the 7.6.4 update to deprecate Windows 10.

**Comment by ggray-cb** [comment]
@malarky, can you review the change I made to make the OS requirements for VMs and containers more general?

**Review by ElliotFrancisHunter — APPROVED** [review]
Happy to approve from the docs side. Tidy and well formatted! Can't spot any 😱 errors.

**Pull request merged**
