### PR TITLE
DOC-4239: Modified partitioning paragraph

### PR DESCRIPTION
**Pull request by tonyjhillman**

### CODE REVIEW

**Review by deepkaran — CHANGES_REQUESTED** [review]
In the first line, please change "increases aggregate query performance" to "increase query performance". Rest looks good.

**Comment by tonyjhillman** [comment]
I think it has to be 'Index Partitioning increases', rather than 'increase', since 'Partitioning' is singular. I could change it to 'Partitioned indexes increase', if that is better.

**Comment by deepkaran** [comment]
Sorry that was a typo. I wanted to say "Index Partitioning increases aggregate query performance" -> "Index Partitioning increases query performance"

**Comment by tonyjhillman** [comment]
Modified and ready to merge for 6.0.

**Review by deepkaran — APPROVED** [review]

**Review by amarantha-k — APPROVED** [review]

**Pull request merged**
