### PR TITLE
DOC-4142

### PR DESCRIPTION
**Pull request by simon-dew**
Update Couchbase Server installation documents to ensure Analytics service is included

### CODE REVIEW

**Review by amarantha-k — APPROVED** [review]

**Comment by amarantha-k** [comment]
Waiting for @eric-schneider's feedback/updates.

**Comment by eric-schneider** [comment]
@amarantha-k I've made the changes, but I don't see an automated build being kicked off for this.

**Review by eric-schneider — APPROVED** [review]

**Comment by jamesnocentini** [comment]
@eric-schneider From what I’ve seen, automated builds on PRs only happen on couchbase/docs-site and couchbase/docs-ui repos.

**Comment by eric-schneider** [comment]
This is ready to merge.

**Pull request merged**
