### PR TITLE
DOC-8667: Restructure Services and Indexes documentation

### PR DESCRIPTION
**Pull request by simon-dew**
- Moved [Views](https://docs-staging.couchbase.com/server/7.0/learn/views/views-intro.html) from Learn section to Reference
- Kept a [single-page overview of all Couchbase indexes](https://docs-staging.couchbase.com/server/7.0/learn/services-and-indexes/indexes/indexes.html) in the Learn section
- Kept [overview of all Couchbase Services](https://docs-staging.couchbase.com/server/7.0/learn/services-and-indexes/services/services.html) in the Learn section
- Moved [Index Service pages](https://docs-staging.couchbase.com/server/7.0/learn/services-and-indexes/indexes/global-secondary-indexes.html) to the Develop section — within Query

Docs issue: [DOC-8667](https://issues.couchbase.com/browse/DOC-8667)

### CODE REVIEW

**Review by amarantha-k — COMMENTED** [review]
Need to move Views API from REST to Views Reference section

**Comment by simon-dew** [comment]
> Need to move Views API from REST to Views Reference section

Done

**Comment by simon-dew** [comment]
Merging this as it is so I can move on to other GSI tickets. Further adjustments can be made in future PRs.

**Comment by simon-dew** [comment]
Updated links to staging docs

**Pull request merged**
