### PR TITLE
MB-48904 Version 7.0 - Need to remove cbdocloader code snippet since

### PR DESCRIPTION
**Pull request by RayOffiah**
Removed snippets and text

### CODE REVIEW

**Comment by RekhaDS** [comment]
The changes looks good to me.

**Comment by RayOffiah** [comment]
👍🏾

From: RekhaDS ***@***.***>
Date: Monday, 29 November 2021 at 18:01
To: couchbase/docs-server ***@***.***>
Cc: Ray Offiah ***@***.***>, Assign ***@***.***>
Subject: Re: [couchbase/docs-server] MB-48904 Version 7.0 - Need to remove cbdocloader code snippet since (PR #2299)

The changes looks good to me.

**Review by maria-robobug — APPROVED** [review]
👍 LGTM

**Comment by RayOffiah** [comment]
Thanks, and Happy New Year!

**Pull request merged**
