### PR TITLE
DOC-7182: Syntax changes for CREATE STATEMENT GA

### PR DESCRIPTION
**Pull request by simon-dew**
The following draft documentation is ready for review:

* [CREATE FUNCTION](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/createfunction.html)
* [EXECUTE FUNCTION](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/execfunction.html)
* [DROP FUNCTION](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/dropfunction.html)
* [User-Defined Functions](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/userfun.html)

Docs issue: [DOC-7182](https://issues.couchbase.com/browse/DOC-7182)

### CODE REVIEW

**Comment by marcogrecopriolo** [comment]
One minor comment - for CREATE FUNCTION ... LANGUAGE JAVASCRIPT ... the object and the library names are strings.
This is explicit in the example given, but is not clarified in the description of the railroad diagram.

One major comment - in 7.0 UDFs has been changed to be collections (or more correctly, scopes) compliant.
We have two types of functions - global, which are the ones described so far, and scoped.
IE you can CREATE FUNCTION default:`travel-sample`.scope1.trains(...) { .... } which would sit under scope1 and would reference collections inside scope1.

The big differentiator between global and scoped functions is query context: global functions are those used when query_context is unset, scoped functions defined inside a particular scope are used when query_context is set to that scope.

Sorry to be the bearer of bad news...

**Comment by simon-dew** [comment]
Updated after review. @marcogrecopriolo if you could please review again. Follow links at the top of this PR to see updated draft documentation. (If you don't see any updates straight away, try refreshing the page.)

**Comment by simon-dew** [comment]
Note that examples do _not_ include explicit global or scoped functions — this is deliberate. Examples will be updated post-beta using updated sample buckets with scopes and collections.

**Comment by marcogrecopriolo** [comment]
looking good

**Review by marcogrecopriolo — APPROVED** [review]

**Comment by simon-dew** [comment]
Update links to staging docs

**Pull request merged**
