### PR TITLE
DOC-12112 no vbucket replica warning

### PR DESCRIPTION
**Pull request by ggray-cb**
This PR addresses DOC-12112 by adding a discussion of the additional warning Couchbase Server shows when trying to hard failover a node with vBuckets that do not have replicas on other nodes. It also fixes IP address issues with the procedures.

You can see the output of these changes [in this preview](https://preview.docs-test.couchbase.com/preview-no-vbucket-replica-warning-7.0/server/7.0/manage/manage-nodes/failover-hard.html#confirm-failover-dialog).

### CODE REVIEW

**Review by bfavini — APPROVED** [review]

**Review by CB-DavidPancic — APPROVED** [review]
Looks great.

I'm assuming these changes aren't limited to 7.0 and affect the other versions' documentations as well?

**Comment by CB-DavidPancic** [comment]
Looks great.

I'm assuming these changes aren't limited to 7.0 and affect the other versions' documentations as well?
________________________________

**Comment by ggray-cb** [comment]
> Looks great. I'm assuming these changes aren't limited to 7.0 and affect the other versions' documentations as well?

They have to be forward ported to all later versions. That hopefully should be quick.

**Comment by CB-DavidPancic** [comment]
Looks like changes are live on each version.

Thanks a lot for the quick work!
________________________________

**Pull request merged**
