### PR TITLE
DOC-9536: Modified description of version compatibiity

### PR DESCRIPTION
**Pull request by tonyjhillman**

### CODE REVIEW

**Comment by tonyjhillman** [comment]
Question: Regarding the asterisked 6.6.0 entries, are these indeed (as it says) for local backup only, or are they for local 'backup and restore' only? Thanks.

**Review by jamesl33 — APPROVED** [review]
LGTM :+1:

**Comment by jamesl33** [comment]
> Question: Regarding the asterisked 6.6.0 entries, are these indeed (as it says) for local backup only, or are they for local 'backup and restore' only? Thanks.

Good question, in theory, the limitation only applies to the backup side (a requirement on the DCP sync-backfill control flag). So I'm quite happy for this to stay as is, a cloud restore should work as expected to 6.5.x, 6.0.x and 5.5.x.

@hyunjuV please let me know if you disagree.

EDIT: Now that I think about it, the same restriction (asterisk) should apply for 6.6.1, 7.0 and 7.1.

**Comment by tonyjhillman** [comment]
Can you verify that I've gotten this right? I've added asterisks to the other versions you've mentioned. Thanks.

**Comment by jamesl33** [comment]
Looks good to me, I think the "6.6.0" and "6.6.1 and above" are now the same though :+1:

**Comment by tonyjhillman** [comment]
I've removed the redundant line from the table. Thanks.

**Pull request merged**
