### PR TITLE
DOC-7505: COLLECTION statements

### PR DESCRIPTION
**Pull request by simon-dew**
The following draft documentation is ready for review:

* [CREATE COLLECTION](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/createcollection.html)
* [DROP COLLECTION](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/dropcollection.html)

Docs issue: [DOC-7505](https://issues.couchbase.com/browse/DOC-7505)

### CODE REVIEW

**Comment by marcogrecopriolo** [comment]
The only comment I would make is that you can still use backticks in cbq or any other places that allows query_context to be specified if you so wished, eg
```
\set -query_context = `travel-sample`.places;
\set -query_context `travel-sample`.places;
\set -query_context "`travel-sample`.places;
```
all work as well as
```
\set -query_context "travel-sample.places";
```
so maybe amend not 1 in both documents to that effect?

**Comment by simon-dew** [comment]
@marcogrecopriolo — when I do
```
cbq> \SET -query_context `travel-sample`.places;
cbq> CREATE COLLECTION beaches;
```

I get error 12003:
```
Keyspace not found in CB datastore: default:`travel-sample` - cause: No bucket named `travel-sample`
```

Similarly, when I do:
```
cbq> \SET -query_context = `travel-sample`.places;
cbq> CREATE COLLECTION beaches;
```

I get the same error:
```
Keyspace not found in CB datastore: default:= `travel-sample` - cause: No bucket named = `travel-sample`
```

(The `places` scope already exists for these examples, of course.)

Is this a bug? I'm using build 2351.

I've left the examples as-is, but removed the note for now.

**Comment by marcogrecopriolo** [comment]
oh! that went in in build 3050 or thereabouts, plus there was a bug with handling the last backick, so to test that you really have to get yourself a fairly recent build.

**Comment by simon-dew** [comment]
Update links to staging docs

**Pull request merged**
