### PR TITLE
DOC-9536for7.0: Updated backup version table

### PR DESCRIPTION
**Pull request by tonyjhillman**

### CODE REVIEW

**Comment by tonyjhillman** [comment]
Checking whether the modifications are correct for 7.0. I've tried to use the X.X.x format for each of the release versions, and have specified 'cloud' storage. Thanks.

**Review by jamesl33 — APPROVED** [review]
Please could you update the PR title before merging, I don't think `DOC-9536for7.0:` is correct.

**Comment by tonyjhillman** [comment]
Title question resolved. Merge pending doc review.

**Review by RayOffiah — COMMENTED** [review]
LGTM 👍🏾

**Review by RayOffiah — APPROVED** [review]

**Pull request merged**
