### PR TITLE
DOC-5002: Modified description of XDCR Compression Type in Advanced S…

### PR DESCRIPTION
**Pull request by tonyjhillman**
…ettings table

### CODE REVIEW

**Review by Chaitra19 — COMMENTED** [review]
No, no. Can't say auto is best compression technology. It's just a configuration parameter. Don't publish this, we will go over it in a call

**Comment by amarantha-k** [comment]
@Chaitra19 Could you please take a look at the updates and approve if no further changes are required? Thanks!

**Review by Chaitra19 — COMMENTED** [review]
There is a change in this behavior, we do not do Snappy from 6.5. Let me confirm if we are backporting that to older versions as well. 
Don't wait on this for beta. But I'll confirm with team and revert.

**Comment by amarantha-k** [comment]
@Chaitra19 Please update the PR if you have a confirmation.

**Pull request closed without merging**
