### PR TITLE
DOC-4320: CE vs EE capability needs to be clearly mentioned for CREATE INDEX

### PR DESCRIPTION
**Pull request by simon-dew**
The following documentation is ready for review:

* [CREATE INDEX › Syntax › WITH Clause](https://simon-dew.github.io/docs-site/DOC-4320/server/6.0/n1ql/n1ql-language-reference/createindex.html#index-with)

Documentation issue: [DOC-4320](https://issues.couchbase.com/browse/DOC-4320)

### CODE REVIEW

**Comment by simon-dew** [comment]
For index placement policy, see [DOC-4321](https://issues.couchbase.com/browse/DOC-4321)

**Review by deepkaran — COMMENTED** [review]
I am unable to view the page - https://simon-dew.github.io/docs-site/DOC-4320/server/6.0/n1ql/n1ql-language-reference/createindex.html#index-with

It says page not found.

**Comment by simon-dew** [comment]
> I am unable to view the page

Hmm. Let me look at it.

**Comment by simon-dew** [comment]
@deepkaran please try again now. For some reason github pages didn't deploy.

**Review by deepkaran — COMMENTED** [review]
1.  In the asynchronous mode, CREATE INDEX starts a task to create the primary index and returns as soon as the task is queued for execution, and then the full index creation operation happens in the background.
a. "primary index" needs to be changed to "index definition". 
b. Instead of "returns as soon as the task is queued for execution, and then the full index creation operation happens in the background.", it would be better to say "returns as soon as the task finishes". And then index needs to be built explicitly using BUILD INDEX command. 

2. You can create multiple identical secondary indexes on a bucket for better index availability and place them on separate nodes using the "nodes" clause.
In EE, replica is the recommended way to do this. In CE, users need to create multiple identical indexes. 

3. num_replica
Point to the link for more details - learn/services-and-indexes/indexes/index-replication.html

4. Using Indexes for Aggregates
Point to the link for more details - learn/services-and-indexes/indexes/index_pushdowns.html#operator-pushdowns

**Comment by simon-dew** [comment]
- [x] "primary index" needs to be changed to "index definition".

- [x] Instead of "returns as soon as the task is queued for execution, and then the full index creation operation happens in the background.", it would be better to say "returns as soon as the task finishes". And then index needs to be built explicitly using BUILD INDEX command.

- [x] In EE, replica is the recommended way to do this. In CE, users need to create multiple identical indexes.

- [x] num_replica
Point to the link for more details

- [x] Using Indexes for Aggregates
Point to the link for more details

**Review by tonyjhillman — APPROVED** [review]

**Pull request merged**
