### PR TITLE
Doc 4114a

### PR DESCRIPTION
**Pull request by tonyjhillman**

### CODE REVIEW

**Comment by tonyjhillman** [comment]
Summary:

Understanding Couchbase and Managing Clusters have now been removed from 
the nav system. Instead, we have new sections named 'Learn' and 
'Manage'.

The conceptual information for Nodes, XDCR, and Security now resides in the 
Learn section. Architecture diagrams called out in overview for Learn section.

The Manage section contains individual subsections for Nodes and Clusters, 
Buckets, Logging, Settings, Groups, XDCR, Security, Backup and Restore, 
Monitor, and Troubleshoot.

The following folders have been removed from the source:

backup-restore 
monitoring 
performance
security 
troubleshooting 
xdcr 
indexes 
views 

The following have been reduced in size, but not yet removed, since they 
each contain a few files used by other areas of the docs:

admin 
clustersetup 
settings 

Links have been updated throughout.

**Comment by tonyjhillman** [comment]
This fixes DOC-4114, 3998, and 4114 for 6.0.

**Comment by amarantha-k** [comment]
Adding @jamiltz to review the page aliases.

**Review by jamesnocentini — APPROVED** [review]
Submitted my review as a PR https://github.com/tonyjhillman/docs-server/pull/1 which has been merged.

**Pull request merged**
