### PR TITLE
Work In Progress: DOC-3944

### PR DESCRIPTION
**Pull request by jamesnocentini**
https://issues.couchbase.com/browse/DOC-3944

### CODE REVIEW

**Comment by tonyjhillman** [comment]
This would be just for the server certificate, is that right? What would we say with reference to the client?

**Comment by tonyjhillman** [comment]
So, the only thing that is different is the path-naming of the respective operating systems? Is that right?

**Comment by jamesnocentini** [comment]
Yes that's right.

**Comment by amarantha-k** [comment]
Is this ready to be merged?

**Comment by tonyjhillman** [comment]
Perry has been asked to take a look.

**Comment by jamesnocentini** [comment]
Preview
- http://couchbase-docs.s3.amazonaws.com/doc-3944/server/6.0/manage/manage-security/configure-server-certificates.html#how-to
- http://couchbase-docs.s3.amazonaws.com/doc-3944/sync-gateway/2.1/deployment-considerations.html#x-509-certificates

**Comment by amarantha-k** [comment]
@jamiltz @tonyjhillman Just checking if there is work pending on this PR.

**Comment by jamesnocentini** [comment]
Closing. It will be fixed in https://github.com/couchbase/docs-server/pull/728.

**Pull request closed without merging**
