### PR TITLE
DOC-8736: Update architecture diagrams for Cheshire Cat

### PR DESCRIPTION
**Pull request by simon-dew**
Updates after PM review of Cheshire Cat documentation:

* Update [Index Service Architecture](https://docs-staging.couchbase.com/server/7.0/learn/services-and-indexes/services/index-service.html#index-service-architecture) — add scopes and collections
* Update [Query Sequence](https://docs-staging.couchbase.com/server/7.0/learn/services-and-indexes/services/query-service.html#query-execution) — add Search Service
* Update [Query Service Architecture](https://docs-staging.couchbase.com/server/7.0/learn/services-and-indexes/services/query-service.html#query-service-architecture) — GSI → Indexes
* Add updated diagram source files to docs-server repo in to `modules/learn/assets/source`

✅ Checked that docs site builds without error and source files are not included in output

Docs issue: [DOC-8736](https://issues.couchbase.com/browse/DOC-8736)

### CODE REVIEW

**Review by tonyjhillman — COMMENTED** [review]
I may not understand - so, you are merging the source files into the repository? Are they some/all changed? I looked at one or two but wasn't certain..

**Comment by simon-dew** [comment]
Sorry for the lack of info @tonyjhillman . Yes, after review by product managers, we needed to update the 3 architecture diagrams listed (and linked) in the description at the top of this pull request.

As part of the review, we also decided it would be useful to have the source files for the diagrams in the same repo, alongside the images, so that any writer can update them when necessary. @amarantha-k pointed me at the source files from your personal repo. I have copied these into `docs-server/modules/learn/assets/source/` — as stated above, it doesn't seem to upset Antora having these files in this non-standard location, and Antora does not copy the source files from this location into the output.

All the source files are taken directly from your repo, and the file names and directory structure is unchanged. The only source files that I have updated for release/7.0 are the three listed above: `indexServiceArchitecture.odg`, `queryExecutionSequence.odg`, and `queryServiceArchiteecture.odg`. I used these source files to generate the updated PNG images.

**Review by amarantha-k — APPROVED** [review]
lgtm

**Comment by tonyjhillman** [comment]
Okay, thanks. Looks good.

**Comment by simon-dew** [comment]
Updated links to staging docs

**Pull request merged**
