### PR TITLE
DOC-6817: Document cluster-level settings

### PR DESCRIPTION
**Pull request by simon-dew**
The following documentation is ready for review:

* [Settings and Parameters](https://simon-dew.github.io/docs-site/DOC-6817/server/6.6/settings/query-settings.html) — reworked to include node-level and cluster-level settings
* [General Settings › Configure General Settings with the CLI › Query Settings via CLI](https://simon-dew.github.io/docs-site/DOC-6817/server/6.6/manage/manage-settings/general-settings.html#query-settings-via-cli) — new section
* [Cluster Query Settings API](https://simon-dew.github.io/docs-site/DOC-6817/server/6.6/rest-api/rest-cluster-query-settings.html) — new REST API reference page
* [Admin REST API › Definitions › Settings](https://simon-dew.github.io/docs-site/DOC-6817/server/6.6/n1ql/n1ql-rest-api/admin.html#_settings) — added links to cluster-level settings

Docs issue: [DOC-6817](https://issues.couchbase.com/browse/DOC-6817)

### CODE REVIEW

**Comment by simon-dew** [comment]
OpenAPI source at [cb-swagger#31](https://github.com/couchbaselabs/cb-swagger/pull/31)

**Review by tonyjhillman — APPROVED** [review]
Settings and Parameters
-----------------------

I don't believe overwritten needs a hyphen.

if a request-level parameters - remove 's'

cURL and CURL both appear. Not sure if this is intended.

Cluster-Level, cluster-level and Cluster-level all appear.

These settings can not be set by cbq. => cannot

To output to a file for editing multiple settings => I'd make the concluding 'For example' a new sentence, or at least separate with heavier punctuation.




admin.html
----------

Each statistic consist => + 's'

**Comment by simon-dew** [comment]
> I don't believe overwritten needs a hyphen.
> 
> if a request-level parameters - remove 's'

Done

> cURL and CURL both appear. Not sure if this is intended.

Standardized on cURL for the command line facility, CURL() for the N1QL function.

> Cluster-Level, cluster-level and Cluster-level all appear.

Standardized on Cluster-Level for title case, Cluster-level for sentence case, cluster-level elsewhere.

> These settings can not be set by cbq. => cannot
> 
> To output to a file for editing multiple settings => I'd make the concluding 'For example' a new sentence, or at least separate with heavier punctuation.
> 
> Each statistic consist => + 's'

Done

**Comment by simon-dew** [comment]
Any comments @sitaramv ?

**Pull request merged**
