### PR TITLE
fix footnote so it is compatible with Asciidoctor 2

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Another way to solve this is to use the shorthand form of the xref macro in the footnote text. For example, `<<n1ql-language-reference/groupby.adoc#,GROUP BY>>`

**Comment by mojavelinux** [comment]
This also needs to be backported to 6.6 and 6.5.

**Review by amarantha-k — APPROVED** [review]

**Comment by mojavelinux** [comment]
@simon-dew or @amarantha-k, will you backport this to 6.6 and 6.5?

**Comment by amarantha-k** [comment]
Yes @mojavelinux. I'll backport to 6.6 and 6.5.

**Pull request merged**
