### PR TITLE
DOC-6631: Update N1QL Cheatsheet document

### PR DESCRIPTION
**Pull request by simon-dew**
Work in progress:

* [Couchbase N1QL Cheatsheet](https://github.com/couchbase/docs-server/blob/e04b6145a1206c7d613ff0cc2e882777e86e344b/modules/n1ql/assets/attachments/cheatsheet.pdf)

Docs issue: [DOC-6631](https://issues.couchbase.com/browse/DOC-6631)

### CODE REVIEW

**Comment by simon-dew** [comment]
I rewrote the existing cheat sheet in AsciiDoc, and converted to PDF using [asciidoctor-pdf.js](https://github.com/Mogztter/asciidoctor-pdf.js). I used this tool because it supports multi-column layouts, unlike the Ruby `asciidoctor-pdf` tool.

I created the `cheatsheet.css` stylesheet to apply the two-column layout and mimic (more or less) the formatting of the original cheat sheet.

I have removed the date and updated the link to the query tutorial. I had to tighten up the wording slightly to get the output to fit on two pages with neat page and column breaks. I have not updated the content in any other way.

### Reproduce

To generate the PDF: 

1. Follow the installation instructions on the [asciidoctor-pdf.js](https://github.com/Mogztter/asciidoctor-pdf.js) page. (You will need node.js version 10.17.0 or later.)

2. Run asciidoctor-pdf.js as follows:

        asciidoctor-pdf ./cheatsheet.adoc

### Issues

- [ ] Update JOIN to ANSI JOIN.
- [x] Not all the examples are from the tutorial bucket, despite the comment at the start.
- [x] Add link to index as a service.
- [ ] Not sure if this is the best location for this file. Might need a separate repo?

**Review by RichardSmedley — COMMENTED** [review]
Layout & format looks good.
Nice to see this sort of thing in the docs.
I guess it should get a check for each release?

**Review by eric-schneider — APPROVED** [review]
fantastic work!

**Comment by simon-dew** [comment]
If we add new N1QL features to the cheat sheet, we're going to have to make sure the version is displayed in the cheat sheet, and keep track of the different versions of the file.

**Comment by simon-dew** [comment]
Binh Le wrote:

> Looks good Simon.

**Pull request merged**
