### PR TITLE
DOC-6169 pinning to 2.7

### PR DESCRIPTION
**Pull request by RichardSmedley**

### CODE REVIEW

**Comment by RichardSmedley** [comment]
Pinning to 2.7 until Java SDK 3.0 has a Search document.

**Comment by RichardSmedley** [comment]
Although I thought this already went in: https://github.com/couchbase/docs-server/commit/780166e17b8eb6967db9bbb85d0fad50aabd902f

**Review by simon-dew — APPROVED** [review]
LGTM 👍 

But it's a shame that the [target page](https://docs.couchbase.com/java-sdk/2.7/full-text-searching-with-sdk.html) has a big link at the top saying "A newer version of this documentation is available" — when you click on the *View Latest* button it takes you to the default welcome page. Is there any chance we could create a dummy page for full text searching with the 3.0 SDK?

(Saying something like, "Coming soon: for now see the 2.7 page [link]")

**Comment by RichardSmedley** [comment]
> But it's a shame that the [target page](https://docs.couchbase.com/java-sdk/2.7/full-text-searching-with-sdk.html) has a big link at the top saying "A newer version of this documentation is available" — when you click on the _View Latest_ button it takes you to the default welcome page. Is there any chance we could create a dummy page for full text searching with the 3.0 SDK?

Heh. It's only a few days, the JVM team are definitely catching up on docs...
 
> (Saying something like, "Coming soon: for now see the 2.7 page [link]")

... the alternative would be to link the .NET Search, but .NET 3.0, although it has a Search page, is still in βετα.
Hmm. Maybe the Node.js page?
Oh well, it's only for a few days!

**Comment by simon-dew** [comment]
> Oh well, it's only for a few days!

That's fine! Please ignore my suggestion in that case.

**Pull request merged**
