### PR TITLE
[DOC-10610]: GCP backup instructions improvements.

### PR DESCRIPTION
**Pull request by RayOffiah**
This change covers additional instructions for setting up a cloud backup on GCP.

You can view a preview at:

https://preview.docs-test.couchbase.com/doc-10610/server/current/manage/manage-backup-and-restore/manage-backup-and-restore.html

(If you need a user and password to access the preview, you will find them here: https://couchbasecloud.atlassian.net/wiki/spaces/DOCS/pages/1971224949/Docs+Team+demo+site+passwords)

### CODE REVIEW

**Comment by cbvipulgupta** [comment]
@RayOffiah For GCP option 1) using id and key looks in good shape 
for 2. using metadata service, i am not sure if it's still being worked or is already under scope of this review request.

For 2) just want to nudge on Hyun-Ju's guidance that users need to ensure the service account is attached to the GCP VM/node being used with the Backup Service.

Let me know once you make the change and we should be good to go then.

**Comment by cbvipulgupta** [comment]
Looks good!

**Review by cbvipulgupta — APPROVED** [review]
Approved!

**Review by ggray-cb — COMMENTED** [review]
Is the preview site up to date? In the preview, under the **Cloud Auth Type**  definition in the GCP section,  there's a Metadata Service subhead that has a single step that says "Hold it."  That doesn;t seem to be in the source.

**Comment by RayOffiah** [comment]
Yup, I forgot to update the preview. It's done now. 👍🏾

**Comment by RayOffiah** [comment]
@cbvipulgupta 
@hyunjuV 

Hi there 👋🏾.

I've finished off the additional instructions related to the metadata option; you can find an updated preview here:

https://preview.docs-test.couchbase.com/doc-10610/server/current/manage/manage-backup-and-restore/manage-backup-and-restore.html

The preview site passwords are kept here (we try not to keep passwords on the PRs – sorry).

https://couchbasecloud.atlassian.net/wiki/spaces/DOCS/pages/1971224949/Docs+Team+demo+site+passwords)

**Review by ggray-cb — APPROVED** [review]

**Review by cbvipulgupta — APPROVED** [review]
Thanks for adding the details for GCP - via Metadata service. Looks good to me

**Pull request merged**
