### PR TITLE
DOC-10036a: Fixed issues for release notes

### PR DESCRIPTION
**Pull request by tonyjhillman**

### CODE REVIEW

**Comment by bkumaran** [comment]
@tonyjhillman - I don't see any reference to magma in release notes.

**Review by sumedhpb — COMMENTED** [review]
Looks good to me (ns-server)

**Comment by tonyjhillman** [comment]
Thanks very much. I have added a ref to magma via https://github.com/couchbase/docs-server/pull/2690.

**Comment by pavan-couchbase** [comment]
@tonyjhillman  

I have a couple of observations. 

This is a FTS bug fix but it appears in the Index section of fixed issues -> https://issues.couchbase.com/browse/MB-51059. 
Smart batching w.r.t the indexing service is missing ->   https://issues.couchbase.com/browse/MB-33546 (DOC ticket -> https://issues.couchbase.com/browse/DOC-9624  )

cc @hrajput89

**Comment by tonyjhillman** [comment]
Thank you. I have put a PR to fix this at https://github.com/couchbase/docs-server/pull/2694. Please take a look and let me know if it's okay.

**Comment by pavan-couchbase** [comment]
I've approved the changes. I've got no other comments on this PR. Looks good to me.

**Pull request merged**
