### PR TITLE
NO ISSUE: Merge release/7.2 into release/7.6

### PR DESCRIPTION
**Pull request by simon-dew**
This PR cherry-picks all changes that have been added to release/7.2 since the release/7.6 branch was created on 2023/06/14.

Release note and "what's new" changes are not merged forward.

Changes which have already been made in release/7.6 are not merged forward.

Preview site: [Couchbase Server](https://preview.docs-test.couchbase.com/merge-72-76/home/server.html)

Credentials for preview site: [Preview docs for internal review](https://couchbasecloud.atlassian.net/wiki/x/dYF_dQ#Preview-docs-for-internal-review)

### CODE REVIEW

**Comment by simon-dew** [comment]
@ggray-cb @RayOffiah @RichardSmedley please can you look at this and check that I haven't accidentally over-written anything in release/7.6?

**Comment by simon-dew** [comment]
Also adding @osfameron and @malarky for the metrics stuff. Please can you look at this and check that I haven't accidentally over-written anything in release/7.6? Thanks

**Review by osfameron — APPROVED** [review]
Metrics part looks 👍 

Suggest getting this merged in ASAP and resolving any issues in subsequent commits.

**Review by RichardSmedley — COMMENTED** [review]
The port forward of my change is fine - but it's only one change, so I won't comment on the remainder. :+1:

**Review by RayOffiah — APPROVED** [review]
Looks fine; nothing seems to be touching the WhatsNew pages and the release note stuff, so it looks good to me. Might have to look at the install page again, but I'll leave it for now.

**Review by malarky — APPROVED** [review]
@simon-dew / @osfameron Agreed, any metrics changes for 7.6 should be applied over the top of the 7.2 ones, can be done once this is in 👍🏻

**Comment by simon-dew** [comment]
Added new commit following review from @osfameron

**Pull request merged**
