### PR TITLE
DOC-7348: Remove getIndexStatus and getIndexStatement endpoints

### PR DESCRIPTION
**Pull request by simon-dew**
The following draft documentation is ready for review:

* Removed pages on `getIndexStatus` and `getIndexStatement` endpoints
* [Index Service API](https://github.com/couchbase/docs-server/blob/f2ca75025945b8d9b87c2ff60842cb1fcd49b594/modules/rest-api/pages/rest-index-service.adoc)
  - removed `getIndexStatus` and `getIndexStatement` endpoints
  - added `api/v1/stats` enpoint
  - added links to `system:indexes` catalog
* [CREATE INDEX](https://github.com/couchbase/docs-server/blob/4a1f2bceec1dd50790c29a65fdc83ed31401ec08/modules/n1ql/pages/n1ql-language-reference/createindex.adoc) — updated link to `system:indexes` catalog
* [ALTER INDEX](https://github.com/couchbase/docs-server/blob/4a1f2bceec1dd50790c29a65fdc83ed31401ec08/modules/n1ql/pages/n1ql-language-reference/alterindex.adoc) — updated link to `system:indexes` catalog

Docs issue: [DOC-7348](https://issues.couchbase.com/browse/DOC-7348)

### CODE REVIEW

**Comment by VarunVelamuri** [comment]
Hi Simon, In Index Service API, for /settings/indexes, the description for GET and POST has to be swapped. Currently, the description for POST is present in GET and the description for GET is present in POST. See pools/default for example

**Comment by VarunVelamuri** [comment]
Not sure if it is possible, but it would be good to provide a hyperlink to system:indexes catalog at the below description:

"To retrieve the status of defined indexes, including the index keys and conditions, you can use the N1QL REST API to query the system:indexes catalog"

**Comment by simon-dew** [comment]
> Not sure if it is possible, but it would be good to provide a hyperlink to system:indexes catalog at the below description:
> 
> "To retrieve the status of defined indexes, including the index keys and conditions, you can use the N1QL REST API to query the system:indexes catalog"

Done. (The link is there, but doesn't show up in the GitHub preview)

**Comment by simon-dew** [comment]
> Hi Simon, In Index Service API, for /settings/indexes, the description for GET and POST has to be swapped. Currently, the description for POST is present in GET and the description for GET is present in POST. See pools/default for example

Moved the description of the available options to POST.

**Review by RichardSmedley — APPROVED** [review]

**Pull request merged**
