### PR TITLE
DOC-9208: [How-to Guides] Query — Prepared Statements

### PR DESCRIPTION
**Pull request by simon-dew**
The following draft documentation is ready for review:

* [Prepared Statements](https://simon-dew.github.io/docs-site/DOC-9208/server/current/guides/prep-statements.html)

Docs issue: [DOC-9208](https://issues.couchbase.com/browse/DOC-9208)

### CODE REVIEW

**Comment by simon-dew** [comment]
Please check SDK examples in particular 🙏

**Comment by maria-robobug** [comment]
Will try to check the SDK examples in a bit.
As a quick comment, it would be preferable if we put these in their respective SDK repos and just referenced them here instead.

**Comment by simon-dew** [comment]
> Will try to check the SDK examples in a bit. As a quick comment, it would be preferable if we put these in their respective SDK repos and just referenced them here instead.

Yes of course. I've referenced SDK examples wherever possible, and raised DOC-10149 to DOC-10152 to address the points where I couldn't reuse SDK examples

**Review by RichardSmedley — APPROVED** [review]
Thanks @simon-dew , if the SDK examples are to migrate eventually, then  LGTM  :+1: 

(but perhaps wait for Maria's +1, in case I missed anything in the code samples.  :thinking: )

**Comment by simon-dew** [comment]
Hi @maria-robobug — just to make life easier for reviewers, I should point out that:

* `adhoc.cs` is based on the [.NET SDK Prepared Statements example](https://docs.couchbase.com/dotnet-sdk/current/concept-docs/n1ql-query.html#prepared-statements-for-query-optimization) with country parameter corrected — see [DOC-10151](https://issues.couchbase.com/browse/DOC-10151)
* `adhoc.js` is based on the [Node.js SDK Prepared Statements example](https://docs.couchbase.com/nodejs-sdk/current/concept-docs/n1ql-query.html#prepared-statements-for-query-optimization) with positional parameter added and syntax adjusted based on [n1ql-queries-scoped.js](https://github.com/couchbase/docs-sdk-nodejs/blob/release/4.1/modules/devguide/examples/nodejs/n1ql-queries-scoped.js#L34-L48) — see [DOC-10150](https://issues.couchbase.com/browse/DOC-10150)
* `adhoc.py` is based on the [Python SDK Prepared Statements example](https://docs.couchbase.com/python-sdk/current/concept-docs/n1ql-query.html#prepared-statements-for-query-optimization) with no changes made — see [DOC-10149](https://issues.couchbase.com/browse/DOC-10149)

**Review by maria-robobug — APPROVED** [review]
👍 LGTM, guess these can be moved to the SDK repos and turned into runnable examples in future...

**Pull request merged**
