### PR TITLE
DOC-11066: Remove prerelease flag

### PR DESCRIPTION
**Pull request by simon-dew**
For release of 7.2.x

See docs issue for other GA release tasks: DOC-11066

### CODE REVIEW

**Comment by yashjanicouch** [comment]
@dgnicholson if this contribution has no conflict with base branch and it is stable please merge it.

**Comment by yashjanidev** [comment]
@dgnicholson if this contribution has no conflict with base branch and it is stable please merge it.

**Review by dgnicholson — APPROVED** [review]

**Comment by simon-dew** [comment]
> @dgnicholson if this contribution has no conflict with base branch and it is stable please merge it.

Apologies @yashjanidev , we misidentified your comment as spam.

**Comment by yashjanidev** [comment]
@simon-dew no problem

**Comment by yashjanidev** [comment]
@simon-dew don't apologize please

**Pull request merged**
