### PR TITLE
DOC-11449: Bucket rank

### PR DESCRIPTION
**Pull request by tonyjhillman**

### CODE REVIEW

**Comment by tonyjhillman** [comment]
NB, pre-built versions, for convenience of review, are located at:

**Bucket Rank Overview** at https://tonyjhillman.github.io/DOC-11449/server/current/learn/clusters-and-availability/rebalance.html

**Creating and Editing Buckets** at https://tonyjhillman.github.io/DOC-11449/server/current/rest-api/rest-bucket-create.html

**What's New** at https://tonyjhillman.github.io/DOC-11449/server/current/introduction/whats-new.html

**Comment by anuthan** [comment]
@bryandmc  Could you review the docs? Thanks.

**Comment by bryandmc** [comment]
This looks good to me

**Comment by tonyjhillman** [comment]
Thanks very much.

**Pull request merged**
