### PR TITLE
DOC-7526: N1QL Collections — Other statements

### PR DESCRIPTION
**Pull request by simon-dew**
The following draft documentation is ready for review.

Updated description of keyspace reference syntax — full description:

* [ALTER INDEX](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/alterindex.html#syntax) — updated from [DOC-7503](https://issues.couchbase.com/browse/DOC-7503)
* [CREATE INDEX](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/createindex.html#syntax)
* [CREATE PRIMARY INDEX](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/createprimaryindex.html#syntax)
* [DROP INDEX](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/dropindex.html#syntax) — updated from [DOC-7503](https://issues.couchbase.com/browse/DOC-7503)
* [DROP PRIMARY INDEX](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/dropprimaryindex.html#syntax)
* [SELECT Syntax](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/select-syntax.html#from-clause)
* [FROM Clause](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/from.html#sec_from-keyspace)

Updated description of keyspace reference syntax — brief description:

* [BUILD INDEX](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/build-index.html#syntax)
* [DELETE](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/delete.html#syntax)
* [GRANT](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/grant.html#syntax)
* [Index Partitioning](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/index-partitioning.html#syntax)
* [Adaptive Indexing](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/adaptive-indexing.html#syntax)
* [Array Indexing](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/indexing-arrays.html#syntax)
* [INFER](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/infer.html#syntax)
* [INSERT](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/insert.html#insert-syntax)
* [MERGE](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/merge.html#syntax)
* [REVOKE](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/revoke.html#syntax)
* [UPDATE](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/update.html#syntax)
* [UPDATE STATISTICS](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/updatestatistics.html#syntax)
* [UPSERT](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-language-reference/upsert.html#syntax)

Other updates to fix broken links and change usage of bucket → keyspace.

Docs issue: [DOC-7526](https://issues.couchbase.com/browse/DOC-7526)

### CODE REVIEW

**Comment by marcogrecopriolo** [comment]
I find a bit weird that the first set of documents splits keyspace-ref into keyspace-path and keyspace-partial, while starting with BUILD INDEX keyspace-ref has a single railroad diagram. At the end of the day, both describe the same object.
This is very much a stylistic choice, but maybe a consistent railroad would be better?

Please also add Bingjie Miao as a reviewer for update statistics - this in particular because major changes have been coded last week that have nod made it into the documentation (sorry to be the bearer of bad news...), namely

- oracle friendly syntax ANALYZE [[COLLECTION|KEYSPACE]]..., ANALYZE INDEX
- ability to drop distributions UPDATE STATISTICS ... DELETE [[COLLECTION|KEYSPACE]]...

On the second point, COLLECTION is now an optional keyword for INFER too.

**Comment by simon-dew** [comment]
Thanks @marcogrecopriolo 

> I find a bit weird that the first set of documents splits keyspace-ref into keyspace-path and keyspace-partial, while starting with BUILD INDEX keyspace-ref has a single railroad diagram. At the end of the day, both describe the same object.
> This is very much a stylistic choice, but maybe a consistent railroad would be better?

Good point, I'll revisit this.

**Comment by simon-dew** [comment]
> Please also add Bingjie Miao as a reviewer for update statistics

CBO documentation changes will be documented by [DOC-7457](https://issues.couchbase.com/browse/DOC-7457)

**Review by marcogrecopriolo — APPROVED** [review]

**Comment by simon-dew** [comment]
Update links to staging docs

**Pull request merged**
