### PR TITLE
DOC-4475: additional statistics for N1QL auditing

### PR DESCRIPTION
**Pull request by simon-dew**
Please see draft documentation here:

* [Admin REST API › GET /admin/stats](https://simon-dew.github.io/docs-site/DOC-4475/server/6.5/n1ql/n1ql-rest-api/admin.html#_get_stats)
* [Admin REST API › GET /admin/stats/{stat}](https://simon-dew.github.io/docs-site/DOC-4475/server/6.5/n1ql/n1ql-rest-api/admin.html#_admin_stats_stat_get)

Yes, there's a typo in the branch name 🙄

### CODE REVIEW

**Comment by simon-dew** [comment]
Column widths in [Definitions](https://simon-dew.github.io/docs-site/DOC-4475/server/6.5/n1ql/n1ql-rest-api/admin.html#_definitions) section need updating.

This needs a separate issue.

**Comment by marcogrecopriolo** [comment]
Are we actually documenting /admin/stats?
I know they are useful, but they are meant to be used by the UI to display all the pretty graphs....
That said, you;d better off getting Johan to review the auditing stats 'cause that's his thing...

**Comment by simon-dew** [comment]
> Are we actually documenting /admin/stats?

Are the new audit statistics shown anywhere in the UI? I don't think they are, but I might have missed something.

This endpoint is already mentioned in other locations in the documentation, and in the UI. For example, `/admin/stats API request` is one of the events that you can audit.

**Comment by j-larson** [comment]
As far as I know they are not shown in the UI. We provided them for separate verfication that the query engine’s auditing is working correctly.

**Comment by simon-dew** [comment]
Are there any further comments on this pull request? If not, I'll merge it.

**Comment by j-larson** [comment]
Fine by me.

**Comment by marcogrecopriolo** [comment]
Fine by me. I'll make unknown.count disappear - it wasn't meant to be there in the first place.

**Pull request merged**
