### PR TITLE
DOC-4818: Correct examples for adaptive indexes

### PR DESCRIPTION
**Pull request by simon-dew**
Please see draft documentation here:

* [Adaptive Index](https://simon-dew.github.io/docs-site/DOC-4818/server/6.0/n1ql/n1ql-language-reference/adaptive-indexing.html)

Major reformatting of syntax diagrams, corrected example queries, updated example results.

### CODE REVIEW

**Comment by sitaramv** [comment]
Don't know what changed but assumed it is correct. Approve

**Comment by simon-dew** [comment]
@sitaramv the focus of this change is described in [DOC-4818](https://issues.couchbase.com/browse/DOC-4818), but as I tested other examples in the Adaptive Index document, I saw that several other examples did not work as described. I have fixed example queries where necessary.

**Comment by sitaramv** [comment]
Approved

**Review by RichardSmedley — APPROVED** [review]
LGTM
(within the limits of my N1QL-fu)
:+1:

**Pull request merged**
