### PR TITLE
Doc 6275 quickstart

### PR DESCRIPTION
**Pull request by jamesneimanconsulting**
@amarantha-k This branch now includes the scala quickstart in its latest commit.

### CODE REVIEW

**Comment by jamesneimanconsulting** [comment]
@amarantha-k I've added another commit to account for both CE and EE editions.

**Comment by jamesneimanconsulting** [comment]
@amarantha-k The Java quickstart has been added to this branch.

**Comment by amarantha-k** [comment]
@jamesneimanconsulting Could you resubmit your commits to the `DOC-6275-quickstart` branch? I see a merge conflict when I tried to change the base, but there conflicts could not be resolved on the web.

**Comment by amarantha-k** [comment]
Closing without merge as this content has been merged through PR#1157

**Pull request closed without merging**
