### PR TITLE
Backport of PR 1960 to use counter instead of built-in example-number…

### PR DESCRIPTION
**Pull request by amarantha-k**
… attribute

### CODE REVIEW

**Comment by mojavelinux** [comment]
As Simon pointed out, this fix doesn't work for both Asciidoctor 1.5.x and Asciidoctor 2. So we either need to make this fix, then make the jump to Asciidoctor 2 (aka the Antora upgrade), or go back and try to find something that works for both using ifeval.

**Review by mojavelinux — APPROVED** [review]

**Review by mojavelinux — CHANGES_REQUESTED** [review]
On further review, I see that there are even problems with this fix. The counter should only be incremented for the "C", not the "Q". Otherwise, the numbers get out of sync.

I can also verify that the fix **does** work for both Asciidoctor 1.5.x and 2.

**Comment by mojavelinux** [comment]
I want to revise my statement again. The use of counters on this page just need to be removed. Counters just weren't designed for this kind of use case. And they are only adding needless complexity anyway since they can only be used in certain cases and not in others. Just sticking to literal numbers would be much more clear, stable, and maintainable.

**Comment by mojavelinux** [comment]
Here's the actual change I recommend applying: https://github.com/couchbase/docs-server/pull/1979

**Review by simon-dew — COMMENTED** [review]
Further to my review of #1979, I think it would be better to rewrite this page not to use numbered code listings at all. Please await my pull request for release/7.0 and backport that.

**Comment by simon-dew** [comment]
Please backport #1984 instead.

**Comment by amarantha-k** [comment]
As noted in the comments, closing this PR without merge.

**Pull request closed without merging**
