### PR TITLE
DOC-4659: Added paragraphs on hard failover effects on Eventing and A…

### PR DESCRIPTION
**Pull request by tonyjhillman**
…nalytics nodes

### CODE REVIEW

**Comment by tonyjhillman** [comment]
This would be a 5.5 merge. I'm assuming that the new paras on Eventing and Analytics would be appropriate for 6.0 and 6.5 also. If that's not the case, please let me know.

**Review by simon-dew — APPROVED** [review]
Looks good overall. The Analytics Service section is approved. I don't know enough about eventing to approve the Eventing Service section.

**Comment by simon-dew** [comment]
Analytics was a developer preview in 5.5, not officially released until 6.0. Please mark the Analytics Service section as developer preview for the 5.5 branch.

**Comment by tonyjhillman** [comment]
Ok I will add a dp note for 5.5.

**Review by maheshnagarajCbase — COMMENTED** [review]
Content for the "Hard Failover Effect on Nodes Running the Eventing Service" section, looks good. Please proceeed.

**Pull request merged**
