### PR TITLE
DOC-4578: Document new pattern-matching functions

### PR DESCRIPTION
**Pull request by simon-dew**
UPDATE: Draft documentation build removed. Please see updated documentation [here](https://docs-staging.couchbase.com/server/6.5/n1ql/n1ql-language-reference/patternmatchingfun.html).

New functions in this pull request: REGEXP_MATCHES(), REGEXP_SPLIT().

### CODE REVIEW

**Review by RichardSmedley — APPROVED** [review]
LGTM :+1:

**Comment by simon-dew** [comment]
I’ll work on clarifying the difference between REGEXP_LIKE and REGEXP_CONTAINS as part of [DOC-4550](https://issues.couchbase.com/browse/DOC-4550).

Other than that, I take that you’re happy for me to merge the REGEXP_MATCHES and REGEXP_SPLIT documentation?

**Pull request merged**
