### PR TITLE
MB-46912: Document Python UDFs — REST API

### PR DESCRIPTION
**Pull request by simon-dew**
Add Analytics Library REST API to the docs-server nav.

* OpenAPI pull request for Analytics Library REST API is at [couchbaselabs/cb-swagger#63](https://github.com/couchbaselabs/cb-swagger/pull/63)
* Gerrit change for Python UDFs, including Analytics Library REST API, is at [cbas-core+155852](http://review.couchbase.org/c/cbas-core/+/155852)

Docs issue: [MB-46912](https://issues.couchbase.com/browse/MB-46912)

### CODE REVIEW

**Comment by osfameron** [comment]
👍  looks good to me, could rewrite the commit to avoid confusion, but not a biggie.

**Review by amarantha-k — APPROVED** [review]
LGTM

**Review by parshimers — APPROVED** [review]
+1

**Comment by simon-dew** [comment]
Do not merge this PR until Gerrit change is merged

**Pull request merged**
