### PR TITLE
Server 5.5.4 release notes draft for review

### PR DESCRIPTION
**Pull request by amarantha-k**

### CODE REVIEW

**Comment by arod1987** [comment]
@evgenymakarenko reviewed query and signed off

**Comment by arod1987** [comment]
@ajaybhullar will review GSI and give his comments

**Comment by ajaybhullar** [comment]
| https://issues.couchbase.com/browse/MB-33664[MB-33664^]
| If you set the default num_replica using setting, it skipped validation during index creation when the node list is presented in the WITH clause.


this one should probably say

It was possible to create an index with less replicas than the default num_replicas if you used nodes_list in the WITH clause with less nodes than the default number of replicas

| https://issues.couchbase.com/browse/MB-32720[MB-32720^]
| Fixed an issue so that the index service does not get stuck during warmup.

If you could elaborate on this one, saying that the index service got stuck because of core dumps or something to that effect that would be great. 

These are the only two under index that I feel should be modified

**Comment by ritamcouchbase** [comment]
Ritam reviewed the ns_server, kv_engine and security.

**Comment by arod1987** [comment]
XDCR, tools and UI look good to me

**Review by arod1987 — CHANGES_REQUESTED** [review]
| https://issues.couchbase.com/browse/MB-33664[MB-33664^]
| If you set the default num_replica using setting, it skipped validation during index creation when the node list is presented in the WITH clause.

this one should probably say

It was possible to create an index with less replicas than the default num_replicas if you used nodes_list in the WITH clause with less nodes than the default number of replicas

| https://issues.couchbase.com/browse/MB-32720[MB-32720^]
| Fixed an issue so that the index service does not get stuck during warmup.

If you could elaborate on this one, saying that the index service got stuck because of core dumps or something to that effect that would be great.

These are the only two under index that I feel should be modified

**Comment by amarantha-k** [comment]
Thanks everyone! Feedback has been incorporated.

**Pull request merged**
