### PR TITLE
DOC-7808: Couchbase Transaction parameters

### PR DESCRIPTION
**Pull request by simon-dew**
The following documentation is ready for review:

* [Settings and Parameters](https://docs-staging.couchbase.com/server/7.0/settings/query-settings.html)
  - New cluster-level settings: `queryMemoryQuota`, `queryNumAtrs`, `queryTxTimeout`, `queryUseCBO`, `queryCleanupClientAttempts`, `queryCleanupLostAttempts`, `queryCleanupWindow`
  - New node-level settings: `atrcollection`, `numatrs`, `cleanupclientattempts`, `cleanuplostattempts`, `cleanupwindow`, `plus-servicers`
  - New request-level parameters: `atrcollection`, `numatrs`
  - Update defaults for `txtimeout`
  - Use of `memory_quota` to control memory use by transactions
* [Cluster Query Settings API](https://docs-staging.couchbase.com/server/7.0/rest-api/rest-cluster-query-settings.html)
  - Copy of cluster-level settings for REST API reference
* [Admin REST API › Resources › Settings](https://docs-staging.couchbase.com/server/7.0/n1ql/n1ql-rest-api/admin.html#_settings_resource)
  - Copy of node-level settings for REST API reference

Docs issue: [DOC-7808](https://issues.couchbase.com/browse/DOC-7808)

### CODE REVIEW

**Comment by simon-dew** [comment]
Upstream OpenAPI pull request: [cb-swagger#54](https://github.com/couchbaselabs/cb-swagger/pull/54)

**Comment by simon-dew** [comment]
- [x] Within a transaction, if any statement involves an FTS index, the scan_consistency is changed internally from SCAN_PLUS to NOT_BOUNDED.

**Comment by sitaramv** [comment]
Only FTS scan_consistency changed

**Review by sitaramv — APPROVED** [review]

**Comment by simon-dew** [comment]
Update links to staging docs

**Pull request merged**
